<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacompras [
    <!ELEMENT listacompras (venta+)>
    <!ELEMENT venta (ventaacredito|ventainmediata)*>
    <!ELEMENT ventaacredito (fechafinpago*,cantidad)>
    <!ELEMENT fechafinpago (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT ventainmediata (cantidad,divisa)>
    <!ELEMENT divisa (#PCDATA)>
]>
<listacompras>
    <venta>
        <ventaacredito>
            <fechafinpago>22-10-2021</fechafinpago>
            <cantidad>21000</cantidad>
        </ventaacredito>
        <ventainmediata>
            <cantidad>1800</cantidad>
            <divisa>euros</divisa>
        </ventainmediata>
        <ventaacredito>
            <cantidad>21000</cantidad>
        </ventaacredito>
    </venta>
</listacompras>